// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPweHNedbsipo8Gd6W2PJn-PxE8rW-Lhg',
    appId: '1:192832049593:web:9c76e5990abd0993336668',
    messagingSenderId: '192832049593',
    projectId: 'flutsuba',
    authDomain: 'flutsuba.firebaseapp.com',
    storageBucket: 'flutsuba.appspot.com',
    measurementId: 'G-SRXX1KMD5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYjU3FiNZayStcNaxuIcuOavD-zlIrvhE',
    appId: '1:192832049593:android:49eb2fddb0ac073f336668',
    messagingSenderId: '192832049593',
    projectId: 'flutsuba',
    storageBucket: 'flutsuba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfmJjmtrkTkRLIEeMzPqp3vG-yPBBughk',
    appId: '1:192832049593:ios:ce0fa6d53e119393336668',
    messagingSenderId: '192832049593',
    projectId: 'flutsuba',
    storageBucket: 'flutsuba.appspot.com',
    iosClientId: '192832049593-nnu0remg74n5ki35vneqqecjcqam1h27.apps.googleusercontent.com',
    iosBundleId: 'lol.hellointernet.flutsuba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfmJjmtrkTkRLIEeMzPqp3vG-yPBBughk',
    appId: '1:192832049593:ios:ce0fa6d53e119393336668',
    messagingSenderId: '192832049593',
    projectId: 'flutsuba',
    storageBucket: 'flutsuba.appspot.com',
    iosClientId: '192832049593-nnu0remg74n5ki35vneqqecjcqam1h27.apps.googleusercontent.com',
    iosBundleId: 'lol.hellointernet.flutsuba',
  );
}
